name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn
      - name: Run linter
        run: yarn run lint
      - name: Run tests
        run: yarn test
      - name: Run build (Check if the build works)
        run: yarn build
